services:
  - type: web
    name: webhook-listener
    env: node
    region: oregon
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node index.js'
    branch: main
    autoDeploy: true
//pushing changes last try
//second try